---
- name: Configure apache2 using multiple child playbooks
  hosts: all
  tasks:
    - name: Call child playbooks for apche
      include_tasks: "{{item}}"
      with_items:
        - install.yml
        - edit_index.yml
        - restart.yml
        - check_apache_response.yml
...
