---
- name: Capture OS info using environment variables
  hosts: all
  tasks:
    - name: Capture the OS name
      debug:
        var: ansible_distribution
    - name: Capture OS version
      debug:
        var: ansible_distribution_version
    - name: Capture Os major version no
      debug:
        var: ansible_distribution_major_version
