---
- name: Implementing loops
  hosts: all
  tasks:
    - name: Install multiple s/w apps
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - tree
        - git
        - maven
