---
- name: Configure apache2/httpd based on OS flavout using environment variables
  hosts: all
  tasks:
    - name: Install apache2 on Ubuntu server
      apt:
        name: apache2
        state: present
        update_cache: yes
      when: ansible_distribution == "Ubuntu"
    - name: Install httpd on Redhat servers
      yum:
        name: httpd
        state: present
        update_cache: yes
      when: ansible_distribution == "RedHat"
    - name: Edit the index.html file
      copy:
        content: "IntelliQ-IT"
        dest: /var/www/html/index.html
    - name: Restart apache2 on ubuntu servers
      service:
        name: apache2
        state: restarted
      when: ansible_distribution == "Ubuntu"
    - name: Restart httpd on redhat servers
      service:
        name: httpd
        state: restarted
      when: ansible_distribution == "RedHat"
    - name: Check apache2/httpd response on all servers
      uri:
        url: "{{item}}"
        status_code: 200
      with_items:
        - http://172.31.16.245
        - http://172.31.24.103
        - http://172.31.20.164
...

